source 'https://rubygems.org'

gem 'jekyll'
gem 'jekyll-minibundle'
gem 'coderay'
gem 'rake'
gem 'jekyll-watch'
gem 'pygments.rb'
gem 'thin'
gem 'webrick'
gem 'jekyll-tagging'
gem 'jekyll-paginate'
gem 'jekyll-redirect-from'